import '@/app/globals.css'
import { AppProvider } from '@/contexts/'
import { PageContainer, PageContent, Title } from './styles'

export const metadata = {
  title: 'DF-Analyzer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <PageContainer>
            <PageContent>
              <Title>Df-Analyzer</Title>
              {children}
            </PageContent>
          </PageContainer>
        </AppProvider>
      </body>
    </html>
  )
}
