import { AppProvider } from '@/contexts/'
import '@/styles/globals.css'

export const metadata = {
  title: 'DF-Analyzer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
